setwd("~/GitHub/tennis_atp")
attach(input[[1]])
temp = list.files(pattern="*.csv")
tennis <- do.call(rbind,lapply(temp[1:107],read.csv))
winners <- as.data.frame(cbind(tennis$winner_rank, tennis$winner_rank - tennis$loser_rank, tennis$winner_age, tennis$winner_rank_points, tennis$winner_rank_points-tennis$loser_rank_points, tennis$winner_hand, tennis$winner_ht, tennis$winner_seed, tennis$surface))
wins<-rep(1,nrow(winners))
losses<-rep(0,nrow(winners))
winners <- as.data.frame(cbind(tennis$winner_rank, tennis$winner_rank - tennis$loser_rank, tennis$winner_age, tennis$winner_rank_points, tennis$winner_rank_points-tennis$loser_rank_points, tennis$winner_hand, tennis$winner_ht, tennis$winner_seed, tennis$surface,wins))
losers <- as.data.frame(cbind(tennis$loser_rank, tennis$loser_rank - tennis$winner_rank, tennis$loser_age, tennis$loser_rank_points, tennis$loser_rank_points-tennis$winner_rank_points, tennis$loser_hand, tennis$loser_ht, tennis$loser_seed, tennis$surface,losses))
colnames(winners)<-c("rank","rankDif","age","rankpts","rankPtDif","hand","ht","seed","surface","wins")
colnames(losers)<-c("rank","rankDif","age","rankpts","rankPtDif","hand","ht","seed","surface","wins")
tennis2<-rbind(winners,losers)
tennis2$hand<-factor(tennis2$hand)
tennis2$surface<-factor(tennis2$surface)
model<-glm(wins~rank+rankDif+age+rankpts+rankPtDif+rank*rankPts,data=tennis2,family="binomial")
predict(model, newdata=df, type="response")
